-- DM reply threading. Self-FK on Message with ON DELETE SET NULL so
-- deleting a parent doesn't cascade-wipe its replies — the replies
-- survive and the UI falls back to "Original message unavailable".
--
-- Hand-rolled (not generated by `prisma migrate dev`) to match the
-- pattern used by add_message_reactions; the shadow DB is drifted from
-- migration history.

ALTER TABLE "Message"
  ADD COLUMN IF NOT EXISTS "replyToMessageId" TEXT;

ALTER TABLE "Message"
  ADD CONSTRAINT "Message_replyToMessageId_fkey"
  FOREIGN KEY ("replyToMessageId") REFERENCES "Message"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

CREATE INDEX IF NOT EXISTS "Message_replyToMessageId_idx"
  ON "Message" ("replyToMessageId");
