// Generated by solidity/scripts/deploy.js after the deploy run.
// Resolved for env=testnet, networkId=1, storage chain=L2 (eid=40245).
// To rebuild without redeploying: rerun the CLI install for this network.

export const WETH_ADDRESS = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2" as const;
export const USDC_ADDRESS = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" as const;
export const USDT_ADDRESS = "0xdAC17F958D2ee523a2206206994597C13D831ec7" as const;
export const CAW_PAIR_ADDRESS = "0x6289Fa33B3542ccc6730599f6F3D87F565Ce5d35" as const;
export const CAW_ADDRESS = "0x56817dc696448135203C0556f702c6a953260411" as const;
export const CAW_NAMES_ADDRESS = "0xFb45Cae2073eA04E3cF31A2D6E55F03737bCA327" as const;
export const CAW_NAME_QUOTER_ADDRESS = "0xbA30c1Ac24C91E0Ff4294315C295825500Ceea78" as const;
export const CAW_PROFILE_LENS_ADDRESS = "0x2aD8c556F7ABf752db022b6EFe8f954c9e140ef5" as const;
export const CAW_NAMES_MINTER_ADDRESS = "0xDa124Dba089839e979347117d76004Be7feBD74B" as const;
export const URI_GENERATOR_ADDRESS = "0xC2F820886149abfdC40457E20F35E3A035228100" as const;
export const NETWORK_MANAGER_ADDRESS = "0x7eE68c573824597FeDd4df38FA30E2D397ec3C07" as const;
export const CAW_NAME_MARKETPLACE_ADDRESS = "0x68bFF54d7597387b8CB0e81C9Cf4DA7f0a253312" as const;
export const CAW_NAMES_L2_MAINNET_ADDRESS = "0x9804b869bFb5E86Ac61748572c40B719d6E0cb37" as const;
export const CAW_ACTIONS_MAINNET_ADDRESS = "0x0b498D4402E8F5bCDD7da7e245B537588263f5Bb" as const;
export const CAW_NAMES_L2_ADDRESS = "0x866bD663cadf2a5bA23Fab2049732F4067301DfA" as const;
export const CAW_ACTIONS_ADDRESS = "0xB305E9014f8058AdDE0faD8A53eb895B50564bEB" as const;
export const CAW_ACTIONS_ARCHIVE_ADDRESS = "0x506c5c09B064fcFf6861B1e08b6530D997715159" as const;
export const CAW_CHALLENGE_RELAY_ADDRESS = "0x166FD4aa0379D01251beFAdcc3646004D5be9e91" as const;
// export const CAW_ACTIONS_ERC1271_ADDRESS = '...' — not deployed for testnet/L2 yet
// export const SMART_EOA_ADDRESS = '...' — not deployed for testnet/L2 yet
