// scripts/backfill-image-variants.ts
//
// Backfill 320 / 640 / 2048 px width variants for feed images uploaded
// before the variant pipeline shipped. Pre-rollout uploads only have the
// original on disk; when a feed grid requests e.g. `<id>_640.webp` via
// srcset the browser gets a 404, producing a broken cell.
//
// The variant naming convention is:  <stem>_<width><ext>
// (mirrors appendWidthSuffix() in imageVariants.ts and the /api/upload/variant
// route, which preserves the base extension regardless of payload mime.)
//
// Resizing uses ffmpeg (already on PATH — same dep as backfill-avatar-thumbs
// and the OG-card renderer). Quality settings match the FE compressImage()
// presets: q 80 (scale: 2–31 for mjpeg/png; quality 0.8 → ~q6 for webp).
//
// GIF handling: re-encoding with ffmpeg would extract only the first frame,
// breaking animation. GIFs are copied unchanged at each target width (the
// browser scales them in CSS). That matches the FE's pass-through path for
// GIFs in compressImage().
//
// Usage:
//   npx tsx scripts/backfill-image-variants.ts              # live run, default dir
//   npx tsx scripts/backfill-image-variants.ts --dry-run    # report only
//   npx tsx scripts/backfill-image-variants.ts --dir /path  # custom dir
//   UPLOADS_DIR=/path npx tsx scripts/backfill-image-variants.ts
//
// Safe to re-run: all existence checks run before any write; already-present
// variants are skipped unconditionally.

import { readdir, readFile, writeFile, access, copyFile, mkdtemp, unlink, rmdir } from 'fs/promises'
import path from 'path'
import os from 'os'
import { execFile } from 'child_process'
import { promisify } from 'util'

const exec = promisify(execFile)

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const DEFAULT_DIR = '/var/www/test.caw.social/uploads/images'

// Feed-image variant widths (96 is avatar-thumb only, not generated here).
const VARIANT_WIDTHS = [320, 640, 2048] as const

// Extensions the variant system handles. Must match what the FE's
// appendWidthSuffix() will request, and what imageVariants.ts documents.
const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif'])

// Matches exactly 8 lowercase hex chars before the extension — the naming
// generated by randomBytes(4).toString('hex') in the upload route. Rejects
// any file that already has a `_<width>` suffix or belongs to a different
// naming scheme (avatars, DM uploads, legacy `<tokenId>_<timestamp>_<hex>` uploads).
const ORIGINAL_PATTERN = /^[0-9a-f]{8}\.(jpg|jpeg|png|webp|gif)$/i

// ffmpeg timeout per resize operation (one file × one width).
const FFMPEG_TIMEOUT_MS = 30_000

// ---------------------------------------------------------------------------
// CLI parsing
// ---------------------------------------------------------------------------

function parseArgs(): { dir: string; dryRun: boolean } {
  const args = process.argv.slice(2)
  let dir = process.env.UPLOADS_DIR || DEFAULT_DIR
  let dryRun = false
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--dry-run') { dryRun = true; continue }
    if (args[i] === '--dir' && args[i + 1]) { dir = args[++i]; continue }
    if (args[i].startsWith('--dir=')) { dir = args[i].slice(6); continue }
  }
  return { dir, dryRun }
}

// ---------------------------------------------------------------------------
// ffmpeg resize helpers
// ---------------------------------------------------------------------------

// Map of extension → ffmpeg output quality flag(s). These mirror the FE
// presets (quality: 0.8 throughout for feed variants):
//   .webp → `-quality 80`      (ffmpeg's -quality for webp is 0–100)
//   .jpg / .jpeg → `-q:v 6`    (ffmpeg MJPEG scale 2–31; ~q6 ≈ quality 0.8)
//   .png → no lossy flag       (PNG is lossless; use -compression_level 6)
const QUALITY_FLAGS: Record<string, string[]> = {
  '.webp': ['-quality', '80'],
  '.jpg':  ['-q:v', '6'],
  '.jpeg': ['-q:v', '6'],
  '.png':  ['-compression_level', '6'],
}

async function resizeImage(srcPath: string, destPath: string, width: number, ext: string): Promise<void> {
  const qualFlags = QUALITY_FLAGS[ext.toLowerCase()] ?? []
  // Scale: fit within `width` on the longest side, keep aspect ratio.
  // Odd pixel dimensions (from lanczos) are rounded down to nearest even
  // number (`trunc(ow/2)*2`) so libx264 / libvpx don't complain if the
  // file ever gets re-used in a video pipeline — harmless for images.
  const filter = `scale='min(${width},iw)':-2:flags=lanczos`
  await exec('ffmpeg', [
    '-y',
    '-i', srcPath,
    '-vf', filter,
    ...qualFlags,
    '-frames:v', '1',
    '-update', '1',   // suppress image2-muxer "more than one frame" warning
    destPath,
  ], { timeout: FFMPEG_TIMEOUT_MS })
}

async function makeVariant(srcPath: string, width: number, ext: string): Promise<Buffer | null> {
  const tmpDir = await mkdtemp(path.join(os.tmpdir(), 'img-variant-'))
  const tmpOut = path.join(tmpDir, `out${ext}`)
  try {
    await resizeImage(srcPath, tmpOut, width, ext)
    return await readFile(tmpOut)
  } catch (err: any) {
    console.warn(`    ffmpeg error: ${err?.message ?? String(err)}`)
    return null
  } finally {
    await unlink(tmpOut).catch(() => {})
    // mkdtemp dir cleanup is best-effort (tmpDir may already be empty)
    await rmdir(tmpDir).catch(() => {})
  }
}

// ---------------------------------------------------------------------------
// Existence check
// ---------------------------------------------------------------------------

async function fileExists(p: string): Promise<boolean> {
  try { await access(p); return true } catch { return false }
}

// ---------------------------------------------------------------------------
// Stats
// ---------------------------------------------------------------------------

type Stats = {
  scanned: number
  already_complete: number
  variants_generated: number
  variants_skipped_exists: number
  failures: { file: string; width: number; reason: string }[]
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const { dir, dryRun } = parseArgs()

  console.log(`[backfill-image-variants] ${dryRun ? 'DRY RUN — ' : ''}dir=${dir}`)

  let entries: string[]
  try {
    entries = await readdir(dir)
  } catch (err: any) {
    console.error(`Cannot read directory ${dir}: ${err.message}`)
    process.exit(1)
  }

  // Filter to files matching the `<8hex>.<ext>` pattern only.
  const originals = entries.filter(f => ORIGINAL_PATTERN.test(f))
  console.log(`  ${entries.length} total entries, ${originals.length} match original pattern`)

  const stats: Stats = {
    scanned: 0,
    already_complete: 0,
    variants_generated: 0,
    variants_skipped_exists: 0,
    failures: [],
  }

  for (const filename of originals) {
    stats.scanned++

    const dot = filename.lastIndexOf('.')
    const stem = filename.slice(0, dot)
    const ext = filename.slice(dot).toLowerCase()

    if (!IMAGE_EXTS.has(ext)) {
      // Shouldn't happen given ORIGINAL_PATTERN, but be defensive.
      console.log(`  skip ${filename}: unrecognised extension`)
      continue
    }

    const srcPath = path.join(dir, filename)
    const isGif = ext === '.gif'

    // Determine which variant widths are already present.
    const missingWidths: number[] = []
    for (const w of VARIANT_WIDTHS) {
      const variantFile = `${stem}_${w}${ext}`
      const exists = await fileExists(path.join(dir, variantFile))
      if (!exists) missingWidths.push(w)
    }

    if (missingWidths.length === 0) {
      stats.already_complete++
      continue
    }

    if (dryRun) {
      for (const w of missingWidths) {
        const action = isGif ? 'copy (gif)' : `resize → ${w}px`
        console.log(`  would generate ${stem}_${w}${ext}  [${action}]`)
        stats.variants_generated++
      }
      continue
    }

    // Read the original once for all widths.
    let srcBuf: Buffer
    try {
      srcBuf = await readFile(srcPath)
    } catch (err: any) {
      console.warn(`  ${filename}: cannot read original — ${err.message}`)
      for (const w of missingWidths) {
        stats.failures.push({ file: filename, width: w, reason: `read error: ${err.message}` })
      }
      continue
    }

    for (const w of missingWidths) {
      const variantFilename = `${stem}_${w}${ext}`
      const destPath = path.join(dir, variantFilename)

      if (isGif) {
        // GIFs: copy original unchanged to each width name. The FE
        // compressImage() passes GIFs through untouched (re-encoding loses
        // animation); the browser CSS-scales them. Copying is still better
        // than serving a 404.
        try {
          await copyFile(srcPath, destPath)
          console.log(`  ${filename} → ${variantFilename}  [gif copy, ${(srcBuf.length / 1024).toFixed(1)}KB]`)
          stats.variants_generated++
        } catch (err: any) {
          console.warn(`  ${filename}: copy failed for _${w}: ${err.message}`)
          stats.failures.push({ file: filename, width: w, reason: `copy error: ${err.message}` })
        }
        continue
      }

      // Non-GIF: resize with ffmpeg.
      const result = await makeVariant(srcPath, w, ext)
      if (!result) {
        stats.failures.push({ file: filename, width: w, reason: 'ffmpeg returned null' })
        continue
      }

      // Skip writing if the file appeared between our existence check and
      // now (concurrent run or very fast retry). This is idempotent.
      if (await fileExists(destPath)) {
        stats.variants_skipped_exists++
        console.log(`  ${filename} → ${variantFilename}  [appeared mid-run, skipped]`)
        continue
      }

      try {
        await writeFile(destPath, result)
        console.log(`  ${filename} → ${variantFilename}  [${w}px, ${(result.length / 1024).toFixed(1)}KB]`)
        stats.variants_generated++
      } catch (err: any) {
        console.warn(`  ${filename}: write failed for _${w}: ${err.message}`)
        stats.failures.push({ file: filename, width: w, reason: `write error: ${err.message}` })
      }
    }
  }

  // ---------------------------------------------------------------------------
  // Summary
  // ---------------------------------------------------------------------------

  console.log('\n[backfill-image-variants] summary')
  console.log(`  files scanned:          ${stats.scanned}`)
  console.log(`  originals already done: ${stats.already_complete}`)
  console.log(`  variants generated:     ${stats.variants_generated}${dryRun ? ' (dry run)' : ''}`)
  console.log(`  variants skipped:       ${stats.variants_skipped_exists}`)
  console.log(`  failures:               ${stats.failures.length}`)

  if (stats.failures.length > 0) {
    console.log('\nfailure details:')
    for (const f of stats.failures) {
      console.log(`  ${f.file} @${f.width}px — ${f.reason}`)
    }
    process.exit(1)
  }
}

main().catch(err => {
  console.error('[backfill-image-variants] fatal:', err)
  process.exit(1)
})
