#!/usr/bin/env bash
# Install a static "coming soon" page at the apex domain.
#
# We deliberately keep this separate from the main install.sh — running a node
# under your apex domain is the common case, while this is the rarer "I want
# the apex to be a marketing page and the node to live on a subdomain"
# arrangement. Run this once for the apex, then run install.sh for your
# subdomain (e.g. testnet.example.com) and you're done.
#
# Usage:
#   sudo bash scripts/coming-soon/install.sh <apex-domain> [cta-url]
#
# Example (use the wildcard cert at /etc/ssl/<apex>/):
#   sudo bash scripts/coming-soon/install.sh caw.social https://testnet.caw.social
#
# Override the cert location:
#   APEX_CERT=/path/to/fullchain.pem APEX_KEY=/path/to/key.pem \
#     sudo bash scripts/coming-soon/install.sh caw.social

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Re-running with sudo..." >&2
  exec sudo -E bash "$0" "$@"
fi

DOMAIN="${1:-}"
CTA_URL="${2:-https://testnet.${DOMAIN}}"

if [[ -z "$DOMAIN" ]]; then
  echo "Usage: $0 <apex-domain> [cta-url]" >&2
  echo "  e.g. $0 caw.social https://testnet.caw.social" >&2
  exit 1
fi

CERT="${APEX_CERT:-/etc/ssl/${DOMAIN}/fullchain.pem}"
KEY="${APEX_KEY:-/etc/ssl/${DOMAIN}/${DOMAIN}.key}"

if [[ ! -f "$CERT" || ! -f "$KEY" ]]; then
  echo "Cert/key not found:" >&2
  echo "  cert: $CERT" >&2
  echo "  key:  $KEY" >&2
  echo "Set APEX_CERT and APEX_KEY env vars to override the paths." >&2
  exit 1
fi

WEBROOT="/var/www/${DOMAIN}-coming-soon"
HERE="$(cd "$(dirname "$0")" && pwd)"

mkdir -p "$WEBROOT"
# Copy the template and substitute the CTA URL. Using `sed` keeps this a
# single dependency-free script — the template ships an https://testnet
# placeholder; we swap in whatever the operator passed.
sed "s|https://testnet.caw.social|${CTA_URL}|g" "${HERE}/index.html" > "${WEBROOT}/index.html"
chown -R www-data:www-data "$WEBROOT"

# Write the server block. Apex 80→443 redirect, 443 serves the static page.
SITES_AVAILABLE="/etc/nginx/sites-available/${DOMAIN}-coming-soon"
SITES_ENABLED="/etc/nginx/sites-enabled/${DOMAIN}-coming-soon"

cat > "$SITES_AVAILABLE" <<EOF
# Auto-generated by scripts/coming-soon/install.sh
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name ${DOMAIN};

    ssl_certificate     ${CERT};
    ssl_certificate_key ${KEY};
    ssl_protocols TLSv1.2 TLSv1.3;
    add_header Strict-Transport-Security "max-age=31536000" always;

    root ${WEBROOT};
    index index.html;

    location / {
        try_files \$uri /index.html;
    }
}
EOF

ln -sf "$SITES_AVAILABLE" "$SITES_ENABLED"

nginx -t
systemctl reload nginx

echo "✓ Coming-soon page deployed for https://${DOMAIN}/ → ${CTA_URL}"
