-- Polls: a Caw can carry an embedded poll via the ::poll:opt1:opt2:...::
-- marker in its text. The marker is parsed off and the options are stored
-- positionally in Poll.options. Votes target by (pollId, optionIndex);
-- editing isn't supported.
--
-- One Poll per Caw (unique cawId). One Vote per (poll, voter); voting again
-- updates the existing row's optionIndex, unvoting deletes the row.
--
-- Hand-rolled to match the existing migration style; not generated by
-- `prisma migrate dev`.

CREATE TABLE IF NOT EXISTS "Poll" (
  "id"          SERIAL PRIMARY KEY,
  "cawId"       INTEGER NOT NULL UNIQUE,
  "options"     TEXT[]  NOT NULL,
  "totalVotes"  INTEGER NOT NULL DEFAULT 0,
  "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"   TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Poll_cawId_fkey" FOREIGN KEY ("cawId") REFERENCES "Caw"("id")
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "Poll_cawId_idx" ON "Poll" ("cawId");

CREATE TABLE IF NOT EXISTS "Vote" (
  "id"          SERIAL PRIMARY KEY,
  "pollId"      INTEGER NOT NULL,
  "voterId"     INTEGER NOT NULL,
  "optionIndex" INTEGER NOT NULL,
  "cawonce"     INTEGER NOT NULL,
  "pending"     BOOLEAN NOT NULL DEFAULT false,
  "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"   TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Vote_pollId_fkey"  FOREIGN KEY ("pollId")  REFERENCES "Poll"("id")
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "Vote_voterId_fkey" FOREIGN KEY ("voterId") REFERENCES "User"("tokenId")
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "Vote_pollId_voterId_key"
  ON "Vote" ("pollId", "voterId");

CREATE INDEX IF NOT EXISTS "Vote_pollId_optionIndex_idx"
  ON "Vote" ("pollId", "optionIndex");

CREATE INDEX IF NOT EXISTS "Vote_voterId_idx" ON "Vote" ("voterId");
