-- Multi-pin rework. Replaces the single-pin Caw.pinnedAt column with a
-- separate PinnedCaw table (one row per pinned post) so users can pin
-- up to 3 posts. The cap isn't enforced here — the read path
-- (caws.ts profile feed) only surfaces the 3 most recently pinned, so
-- if parallel pin txs slip past the cap, the older rows just don't
-- render until the user unpins one of the visible 3.
--
-- Hand-rolled (not generated by `prisma migrate dev`) to match the
-- pattern used by other migrations — the local shadow DB is drifted
-- from migration history.

-- 1) Drop the old single-pin column + index. IF EXISTS / DROP INDEX
--    IF EXISTS so this migration is idempotent against environments
--    that never ran the prior add_caw_pinned_at migration.
DROP INDEX IF EXISTS "Caw_userId_pinnedAt_idx";
ALTER TABLE "Caw" DROP COLUMN IF EXISTS "pinnedAt";

-- 2) Cached counter on User. Mirrors bookmarkCount / cawCount pattern.
ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "pinnedCawCount" INTEGER NOT NULL DEFAULT 0;

-- 3) New table. `pending` mirrors Like.pending semantics: optimistic
--    inserts set true, indexer flips to false on confirm, tx-fail
--    rollback either deletes (pi:) or flips back (xpi:).
CREATE TABLE IF NOT EXISTS "PinnedCaw" (
    "id"        SERIAL          PRIMARY KEY,
    "userId"    INTEGER         NOT NULL,
    "cawId"     INTEGER         NOT NULL,
    "pending"   BOOLEAN         NOT NULL DEFAULT FALSE,
    "createdAt" TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PinnedCaw_userId_fkey" FOREIGN KEY ("userId")
        REFERENCES "User"("tokenId") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PinnedCaw_cawId_fkey"  FOREIGN KEY ("cawId")
        REFERENCES "Caw"("id")        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "PinnedCaw_userId_cawId_key"
    ON "PinnedCaw" ("userId", "cawId");
CREATE INDEX IF NOT EXISTS "PinnedCaw_userId_createdAt_idx"
    ON "PinnedCaw" ("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "PinnedCaw_cawId_idx"
    ON "PinnedCaw" ("cawId");
