ALTER TABLE "Action" ADD COLUMN IF NOT EXISTS "txHash" TEXT;
ALTER TABLE "Action" ADD COLUMN IF NOT EXISTS "blockNumber" INTEGER;
ALTER TABLE "Action" ADD COLUMN IF NOT EXISTS "submitterAddress" TEXT;
