// Configure the media-storage reverse-proxy nginx vhost.
//
// When the install's client/.env has MEDIA_STORAGE_BACKEND=filebase plus
// FILEBASE_BUCKET set (and a MEDIA_PUBLIC_URL_BASE that names a hostname
// we control), we write /etc/nginx/sites-available/<media-host> with a
// reverse-proxy block that:
//   1. terminates TLS using the same cert the main domain uses (wildcard
//      preferred — falls back to per-host certbot if needed),
//   2. proxies /uploads/* → https://<bucket>.s3.filebase.io/<prefix>/*
//      where <prefix> is the install's main hostname so multiple installs
//      can share one bucket,
//   3. caches 30d on disk to keep Filebase egress bills small.
//
// Idempotent: re-running with the same config leaves the file unchanged.
// Running with no Filebase env vars is a silent no-op.

import fs from 'fs'
import path from 'path'
import { execSync } from 'child_process'
import ora from 'ora'
import { section, dim, brand, success, warn } from '../utils/ui.js'

const MARKER = '# managed-by: caw configure-media-nginx'

/**
 * Read a single key from a .env-style file. Returns the unquoted value or
 * null if the key is missing / file doesn't exist.
 */
function readEnvKey(envPath, key) {
  if (!fs.existsSync(envPath)) return null
  const txt = fs.readFileSync(envPath, 'utf8')
  const re = new RegExp(`^${key}=(.+)$`, 'm')
  const m = re.exec(txt)
  if (!m) return null
  return m[1].replace(/^["']|["']$/g, '').trim() || null
}

function hostnameOf(url) {
  try { return new URL(url).hostname } catch { return null }
}

/**
 * Try to find a usable cert for `host`. Mirrors detectParentWildcard() in
 * nginx.js so any cert layout that works there works here too:
 *   1. /etc/ssl/<parent-domain>/ with cert in {fullchain,cert}.pem and key
 *      in {<parent>.key, privkey.pem, private.key}.
 *   2. /etc/letsencrypt/live/<host>/{fullchain,privkey}.pem — per-host LE.
 * Returns { certPath, keyPath, source } or null.
 */
function findCertFor(host) {
  const labels = host.split('.')
  // Walk parent labels: s.caw.social → caw.social → social
  for (let i = 1; i < labels.length; i++) {
    const parent = labels.slice(i).join('.')
    const dir = `/etc/ssl/${parent}`
    if (!fs.existsSync(dir)) continue
    const certPath = ['fullchain.pem', 'cert.pem']
      .map(n => path.join(dir, n)).find(p => fs.existsSync(p))
    const keyPath = [`${parent}.key`, 'privkey.pem', 'private.key']
      .map(n => path.join(dir, n)).find(p => fs.existsSync(p))
    if (certPath && keyPath) {
      return { certPath, keyPath, source: `wildcard at ${dir}` }
    }
  }
  const leDir = `/etc/letsencrypt/live/${host}`
  const leCert = path.join(leDir, 'fullchain.pem')
  const leKey = path.join(leDir, 'privkey.pem')
  if (fs.existsSync(leCert) && fs.existsSync(leKey)) {
    return { certPath: leCert, keyPath: leKey, source: `letsencrypt at ${leDir}` }
  }
  return null
}

// nginx 1.25.1+ wants `listen 443 ssl;` + standalone `http2 on;`.
// Older nginx (1.24 on Ubuntu 24.04, 1.18 on Ubuntu 22.04) reject `http2 on;`
// and want the legacy `listen 443 ssl http2;` one-liner. Mirrors the same
// detection in nginx.js so the two CLI steps stay in sync.
function detectNginxHttp2DirectiveSupport() {
  try {
    const out = execSync('nginx -v 2>&1', { encoding: 'utf8' })
    const m = out.match(/nginx\/(\d+)\.(\d+)\.(\d+)/)
    if (!m) return false
    const [, major, minor] = m.map(Number)
    return major > 1 || (major === 1 && minor >= 25)
  } catch {
    return false
  }
}

function renderConf({ mediaHost, bucket, prefix, certPath, keyPath, http2OnDirective }) {
  const upstreamHost = `${bucket}.s3.filebase.io`
  // Trailing slash on proxy_pass strips the matched location prefix, so
  // /uploads/foo/bar.webp -> https://<bucket>.s3.filebase.io/<prefix>/foo/bar.webp
  const upstream = `https://${upstreamHost}/${prefix ? `${prefix}/` : ''}`
  const tlsListen = http2OnDirective
    ? `    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;`
    : `    listen 443 ssl http2;
    listen [::]:443 ssl http2;`
  return `${MARKER}
# Auto-generated by caw cli. Edit at your own risk — re-running
# 'caw update' will overwrite changes.

proxy_cache_path /var/cache/nginx/filebase_${mediaHost.replace(/\./g, '_')} levels=1:2 keys_zone=filebase_${mediaHost.replace(/[^a-z0-9]/gi, '_')}:50m max_size=10g inactive=60d use_temp_path=off;

server {
    listen 80;
    listen [::]:80;
    server_name ${mediaHost};
    return 301 https://$host$request_uri;
}

server {
${tlsListen}
    server_name ${mediaHost};

    ssl_certificate     ${certPath};
    ssl_certificate_key ${keyPath};

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    add_header Strict-Transport-Security "max-age=31536000" always;

    # Block everything except the upload paths — this vhost exists only to
    # proxy to Filebase, not to serve a frontend.
    location = / { return 404; }

    location /uploads/ {
        proxy_pass ${upstream};
        proxy_set_header Host ${upstreamHost};
        proxy_ssl_server_name on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;

        # Strip cookies + auth on the way out — Filebase doesn't want them
        # and forwarding them makes proxy_cache useless (each Cookie value
        # would create a separate cache key).
        proxy_set_header Cookie "";
        proxy_set_header Authorization "";

        proxy_cache filebase_${mediaHost.replace(/[^a-z0-9]/gi, '_')};
        proxy_cache_valid 200 30d;
        proxy_cache_valid 404 5m;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        proxy_cache_lock on;
        add_header X-Cache-Status $upstream_cache_status;
        add_header Cache-Control "public, max-age=31536000, immutable";

        # Don't pass the X-Forwarded-* headers — Filebase ignores them and
        # they bloat the request.
        proxy_set_header X-Forwarded-For "";
        proxy_set_header X-Forwarded-Proto "";
    }
}
`
}

/**
 * Top-level: detect Filebase config in client/.env, write the vhost if
 * needed, reload nginx. Returns a small status object so the caller can
 * decide whether to mention this in its output.
 */
export async function configureMediaNginx(installDir) {
  const envPath = path.join(installDir, 'client', '.env')

  const backend = readEnvKey(envPath, 'MEDIA_STORAGE_BACKEND')
  if (backend !== 'filebase') {
    return { status: 'skipped', reason: 'MEDIA_STORAGE_BACKEND is not filebase' }
  }

  const bucket = readEnvKey(envPath, 'FILEBASE_BUCKET')
  const publicBase = readEnvKey(envPath, 'MEDIA_PUBLIC_URL_BASE')
  if (!bucket) {
    return { status: 'incomplete', reason: 'FILEBASE_BUCKET is missing' }
  }
  if (!publicBase) {
    return { status: 'incomplete', reason: 'MEDIA_PUBLIC_URL_BASE is missing — required to derive the media hostname' }
  }
  const mediaHost = hostnameOf(publicBase)
  if (!mediaHost) {
    return { status: 'incomplete', reason: `MEDIA_PUBLIC_URL_BASE is not a valid URL: ${publicBase}` }
  }

  // Filebase is fronted by our nginx, which we can only configure as root.
  const isRoot = process.getuid && process.getuid() === 0
  if (!isRoot) {
    console.log(warn(`  Filebase configured for ${brand(mediaHost)} but caw isn't running as root — skipping nginx setup.`))
    console.log(dim(`  Re-run 'sudo caw update' (or 'sudo caw install') to wire up the reverse proxy.`))
    return { status: 'skipped', reason: 'not root' }
  }

  // Derive the bucket-side prefix (per-install isolation). Mirror what the
  // backend's mediaStorage.ts does: fall back to FILEBASE_KEY_PREFIX, else
  // hostname-of-publicUrl. publicUrl is SHORTURL_DOMAIN at runtime, but at
  // CLI time we can read the same .env to get it.
  const prefixOverride = readEnvKey(envPath, 'FILEBASE_KEY_PREFIX')
  const shortUrlDomain = readEnvKey(envPath, 'SHORTURL_DOMAIN')
  const prefix = (prefixOverride || (shortUrlDomain ? hostnameOf(shortUrlDomain) : null) || '').replace(/^\/+|\/+$/g, '')

  const cert = findCertFor(mediaHost)
  if (!cert) {
    console.log(warn(`  No TLS cert found for ${brand(mediaHost)}.`))
    console.log(dim(`  Looked for /etc/ssl/<parent>/{fullchain,cert}.pem + {<parent>.key,privkey,private}.key, and /etc/letsencrypt/live/${mediaHost}/.`))
    console.log(dim(`  Issue one with: certbot --nginx -d ${mediaHost}`))
    console.log(dim(`  Then re-run 'caw update' to write the reverse-proxy block.`))
    return { status: 'no-cert', mediaHost }
  }

  const http2OnDirective = detectNginxHttp2DirectiveSupport()
  const conf = renderConf({ mediaHost, bucket, prefix, certPath: cert.certPath, keyPath: cert.keyPath, http2OnDirective })
  const sitesAvailable = `/etc/nginx/sites-available/${mediaHost}`
  const sitesEnabled = `/etc/nginx/sites-enabled/${mediaHost}`

  // proxy_cache_path needs the parent directory to exist before nginx -t
  // will succeed. nginx workers (www-data) need to be able to write under
  // it. A fresh Ubuntu install has no /var/cache/nginx at all, so create
  // it here.
  if (!fs.existsSync('/var/cache/nginx')) {
    fs.mkdirSync('/var/cache/nginx', { recursive: true })
    try { execSync('chown www-data:www-data /var/cache/nginx', { stdio: 'pipe' }) }
    catch { /* if chown fails (e.g. www-data isn't the worker user), nginx
                will still try to mkdir at start under whatever user is in
                its config; surface that via nginx -t below */ }
  }

  // Refuse to clobber a hand-managed file. The marker comment is our
  // signal that this file came from us.
  const existing = fs.existsSync(sitesAvailable) ? fs.readFileSync(sitesAvailable, 'utf8') : null
  if (existing && !existing.startsWith(MARKER)) {
    console.log(warn(`  ${sitesAvailable} exists and was not written by caw — leaving it alone.`))
    console.log(dim(`  If you want caw to manage this file, delete it and re-run 'caw update'.`))
    return { status: 'foreign-file', mediaHost }
  }

  // Idempotency check: skip the heavy work only when ALL of (file content
  // matches, symlink in place, nginx already loaded a working config).
  // The "symlink in place" check is what we got wrong before — a file
  // that matched but no symlink left the vhost inactive forever. The
  // nginx-test belt-and-braces is cheap and surfaces problems like a
  // missing /var/cache/nginx that earlier attempts left behind.
  const symlinkPresent = fs.existsSync(sitesEnabled)
  if (existing === conf && symlinkPresent) {
    try {
      execSync('nginx -t', { stdio: 'pipe' })
      return { status: 'unchanged', mediaHost }
    } catch {
      // Fall through to the rewrite-and-reload path so we recover from
      // a state where nginx -t fails for unrelated reasons we can fix.
    }
  }

  section('Media reverse-proxy (Filebase)')
  console.log(dim(`  ${mediaHost} → https://${bucket}.s3.filebase.io/${prefix ? prefix + '/' : ''}`))
  console.log(dim(`  TLS: ${cert.source}`))
  if (prefix) console.log(dim(`  bucket prefix: ${prefix} (per-install isolation)`))

  const spinner = ora('Writing media-host server block...').start()
  try {
    fs.writeFileSync(sitesAvailable, conf)
    if (!fs.existsSync(sitesEnabled)) fs.symlinkSync(sitesAvailable, sitesEnabled)
    spinner.succeed(`Wrote ${sitesAvailable}`)
  } catch (e) {
    spinner.fail('Failed to write media nginx config')
    throw e
  }

  const reload = ora('Testing + reloading nginx...').start()
  try {
    execSync('nginx -t', { stdio: 'pipe' })
    execSync('systemctl reload nginx', { stdio: 'pipe' })
    reload.succeed('nginx reloaded')
  } catch (e) {
    reload.fail('nginx config test failed')
    console.log(warn(`  Inspect with: nginx -t`))
    throw e
  }

  console.log(success(`  ${mediaHost} is live and proxying to Filebase.`))
  return { status: 'written', mediaHost }
}
