// src/api/shared/mockData.ts
import { ShapedCaw } from './cawUtils'

export const mockCawItems: ShapedCaw[] = [
  {
    id: "1",
    timestamp: new Date().toISOString(),
    content: "Just discovered the amazing potential of decentralized social media! The future is here and it's built on blockchain technology. #CawProtocol #Web3",
    user: { tokenId: 1, username: "cawuser1", image: "https://example.com/avatar.jpg" },
    hasLiked: true,
    hasRecawed: false,
    commentCount: 1240,
    recawCount: 8900,
    likeCount: 15600,
    cawonce: 1,
    hashtags: ["CawProtocol", "Web3"],
    parent: null,
  },
  {
    id: "2",
    timestamp: new Date(Date.now() - 14400000).toISOString(),
    content: "Building the next generation of social platforms with Caw Protocol. The community-driven approach is revolutionary!",
    user: { tokenId: 2, username: "blockchaindev", image: "https://example.com/avatar2.jpg" },
    hasLiked: false,
    hasRecawed: false,
    commentCount: 2340,
    recawCount: 45000,
    likeCount: 1560000,
    cawonce: 2,
    hashtags: [],
    parent: null,
  },
  {
    id: "3",
    timestamp: new Date(Date.now() - 21600000).toISOString(),
    content: "The staking rewards on Caw Protocol are incredible! Earning while participating in the ecosystem. This is how social media should work.",
    user: { tokenId: 3, username: "cryptoenthusiast", image: "https://example.com/avatar3.jpg" },
    hasLiked: false,
    hasRecawed: false,
    commentCount: 1500,
    recawCount: 28000,
    likeCount: 890000,
    cawonce: 3,
    hashtags: [],
    parent: null,
  },
  {
    id: "4",
    timestamp: new Date(Date.now() - 28800000).toISOString(),
    content: "The decentralized approach to social media is exactly what we needed. No more centralized control! 🌐 #DecentralizedFreedom",
    user: { tokenId: 4, username: "web3builder", image: "https://example.com/avatar4.jpg" },
    hasLiked: false,
    hasRecawed: false,
    commentCount: 125,
    recawCount: 1900,
    likeCount: 67000,
    cawonce: 4,
    hashtags: ["DecentralizedFreedom"],
    parent: null,
  },
  {
    id: "5",
    timestamp: new Date(Date.now() - 36000000).toISOString(),
    content: "The community here is amazing! Everyone is so supportive and the technology is mind-blowing 💙 #CawProtocol #Community",
    user: { tokenId: 5, username: "cawcommunity", image: "https://example.com/avatar5.jpg" },
    hasLiked: false,
    hasRecawed: false,
    commentCount: 67,
    recawCount: 1400,
    likeCount: 4300,
    cawonce: 5,
    hashtags: ["CawProtocol", "Community"],
    parent: null,
  },
  {
    id: "6",
    timestamp: new Date(Date.now() - 43200000).toISOString(),
    content: "Staking CAW tokens and earning rewards while supporting the network! This is the future of social media 🎯",
    user: { tokenId: 6, username: "decentralized", image: "https://example.com/avatar6.jpg" },
    hasLiked: false,
    hasRecawed: false,
    commentCount: 980,
    recawCount: 22000,
    likeCount: 7800,
    cawonce: 6,
    hashtags: [],
    parent: null,
  }
]

export const userMockItems: ShapedCaw[] = [
  {
    id: "user1",
    timestamp: new Date().toISOString(),
    content: "Just exploring the Caw Protocol ecosystem! The decentralized social media revolution is here 🚀",
    user: { tokenId: 1, username: "user", image: "https://example.com/user-avatar.jpg" },
    hasLiked: false,
    hasRecawed: false,
    commentCount: 5,
    recawCount: 12,
    likeCount: 24,
    cawonce: 1,
    hashtags: [],
    parent: null,
  },
  {
    id: "user2",
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    content: "The community here is amazing! Everyone is so supportive and the technology is mind-blowing 💙 #CawProtocol #Community",
    user: { tokenId: 1, username: "user", image: "https://example.com/user-avatar.jpg" },
    hasLiked: false,
    hasRecawed: false,
    commentCount: 8,
    recawCount: 15,
    likeCount: 31,
    cawonce: 2,
    hashtags: ["CawProtocol", "Community"],
    parent: null,
  },
  {
    id: "user3",
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    content: "Minting usernames on Caw Protocol is so smooth! The gas fees are reasonable and the process is intuitive ✨",
    user: { tokenId: 1, username: "user", image: "https://example.com/user-avatar.jpg" },
    hasLiked: false,
    hasRecawed: false,
    commentCount: 3,
    recawCount: 7,
    likeCount: 18,
    cawonce: 3,
    hashtags: [],
    parent: null,
  },
  {
    id: "user4",
    timestamp: new Date(Date.now() - 5400000).toISOString(),
    content: "Staking CAW tokens and earning rewards while supporting the network! This is the future of social media 🎯",
    user: { tokenId: 1, username: "user", image: "https://example.com/user-avatar.jpg" },
    hasLiked: false,
    hasRecawed: false,
    commentCount: 6,
    recawCount: 9,
    likeCount: 22,
    cawonce: 4,
    hashtags: [],
    parent: null,
  },
  {
    id: "user5",
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    content: "The decentralized approach to social media is exactly what we needed. No more centralized control! 🌐 #DecentralizedFreedom",
    user: { tokenId: 1, username: "user", image: "https://example.com/user-avatar.jpg" },
    hasLiked: false,
    hasRecawed: false,
    commentCount: 4,
    recawCount: 11,
    likeCount: 27,
    cawonce: 5,
    hashtags: ["DecentralizedFreedom"],
    parent: null,
  }
]

export function createHashtagMockCaw(hashtagName: string, index: number): ShapedCaw {
  const baseTimestamp = Date.now() - (index * 7200000) // 2 hours apart

  return {
    id: `hash${index + 1}`,
    timestamp: new Date(baseTimestamp).toISOString(),
    content: index === 0
      ? `Just discovered the amazing potential of #${hashtagName}! The future is here and it's built on blockchain technology. #CawProtocol #Web3`
      : `The #${hashtagName} community is growing every day! Love to see the innovation happening here. 🚀`,
    user: {
      tokenId: index + 1,
      username: index === 0 ? "cawuser1" : "blockchaindev",
      image: `https://example.com/avatar${index + 1}.jpg`
    },
    hasLiked: false,
    hasRecawed: false,
    commentCount: index === 0 ? 8 : 15,
    recawCount: index === 0 ? 12 : 28,
    likeCount: index === 0 ? 24 : 67,
    cawonce: index + 1,
    hashtags: index === 0 ? [hashtagName, "CawProtocol", "Web3"] : [hashtagName],
    parent: null,
  }
}

export const mockTrendingHashtags = [
  { name: "CawProtocol", usageCount: 2340000 },
  { name: "Web3", usageCount: 1890000 },
  { name: "DeFi", usageCount: 987000 },
  { name: "NFT", usageCount: 856000 },
  { name: "Blockchain", usageCount: 743000 },
  { name: "Crypto", usageCount: 692000 },
  { name: "DecentralizedSocial", usageCount: 578000 },
  { name: "Layer2", usageCount: 456000 },
  { name: "Ethereum", usageCount: 412000 },
  { name: "Community", usageCount: 387000 }
]