// Tiny in-house i18n. We avoid react-i18next because:
//   - Catalogs are simple flat JSON, generated by AI from en.json.
//   - We don't need namespaces, suspense boundaries, or HMR scopes.
//   - Bundle weight stays trivial (~1kb of runtime, no extra deps).
//
// Usage:
//   const t = useT()
//   <h1>{t('settings.title')}</h1>
//   <p>{t('greeting.with_name', { name: user.displayName })}</p>
//   <p>{t('likes.count', { count: 3 })}</p>   // pluralization
//
// Conventions:
//   - Keys are lowercase dot-separated (page.section.thing).
//   - Variables use {{name}} placeholders.
//   - For pluralization, store both <key>_one and <key>_other; t() picks
//     based on `count` in the vars object. Falls back to <key> if either
//     suffix is missing.
//   - English (en.json) is the source of truth and the fallback for
//     missing keys in other locales.

import en from './locales/en.json'

export type Catalog = Record<string, string>

// English is loaded statically — it's the fallback for every other
// locale and is also the catalog used at first render before any
// async catalog has loaded.
export const EN_CATALOG: Catalog = stripMeta(en as Record<string, unknown>)

// Lazy importers per locale. Vite tree-shakes unused entries from the
// final bundle; only the catalog the user actually selects is fetched.
// New languages added in src/constants/languages.ts also need an entry
// here AND a matching <code>.json file in src/i18n/locales/.
const LOADERS: Record<string, () => Promise<{ default: Record<string, unknown> }>> = {
  en: () => Promise.resolve({ default: en as Record<string, unknown> }),
  es: () => import('./locales/es.json'),
  zh: () => import('./locales/zh.json'),
  hi: () => import('./locales/hi.json'),
  ar: () => import('./locales/ar.json'),
  pt: () => import('./locales/pt.json'),
  ru: () => import('./locales/ru.json'),
  ja: () => import('./locales/ja.json'),
  de: () => import('./locales/de.json'),
  fr: () => import('./locales/fr.json'),
  ko: () => import('./locales/ko.json'),
  it: () => import('./locales/it.json'),
  tr: () => import('./locales/tr.json'),
  pl: () => import('./locales/pl.json'),
  nl: () => import('./locales/nl.json'),
  vi: () => import('./locales/vi.json'),
  th: () => import('./locales/th.json'),
  id: () => import('./locales/id.json'),
  uk: () => import('./locales/uk.json'),
  he: () => import('./locales/he.json'),
}

export function hasLocale(code: string): boolean {
  return code in LOADERS
}

export async function loadCatalog(code: string): Promise<Catalog> {
  const loader = LOADERS[code]
  if (!loader) return EN_CATALOG
  try {
    const mod = await loader()
    return stripMeta(mod.default)
  } catch (err) {
    console.warn(`[i18n] failed to load catalog ${code}:`, err)
    return EN_CATALOG
  }
}

function stripMeta(raw: Record<string, unknown>): Catalog {
  const out: Catalog = {}
  for (const [k, v] of Object.entries(raw)) {
    if (k.startsWith('_')) continue
    if (typeof v === 'string') out[k] = v
  }
  return out
}

export interface TVars {
  count?: number
  [key: string]: string | number | undefined
}

/**
 * Look up a translation in `catalog`, falling back to `EN_CATALOG`, then
 * to the key itself. Substitutes {{var}} placeholders. Pluralizes via
 * <key>_one / <key>_other suffixes when `vars.count` is set.
 *
 * Pure function — wrapped by useT() for components, but also callable
 * standalone if you have a catalog reference (e.g. from a non-React
 * code path).
 */
export function translate(catalog: Catalog, key: string, vars?: TVars): string {
  let lookupKey = key
  if (vars && typeof vars.count === 'number') {
    const suffix = vars.count === 1 ? '_one' : '_other'
    if ((key + suffix) in catalog || (key + suffix) in EN_CATALOG) {
      lookupKey = key + suffix
    }
  }

  const raw = catalog[lookupKey] ?? EN_CATALOG[lookupKey] ?? catalog[key] ?? EN_CATALOG[key] ?? key

  if (!vars) return raw
  return raw.replace(/\{\{(\w+)\}\}/g, (_, name) => {
    const v = vars[name]
    return v === undefined ? `{{${name}}}` : String(v)
  })
}
