-- DM message reactions + per-identity customizable defaults.
--
-- MessageReaction: one row per (message, user, emoji). The (messageId,
-- userId, emoji) UNIQUE constraint serves the toggle behavior — second
-- tap on the same emoji deletes by that key.
--
-- DmIdentity.defaultDmReactions: per-user override list. Empty array
-- means "use server defaults"; otherwise expected to hold exactly five
-- emojis (UI clamps; no DB-level length check).
--
-- Hand-rolled (not generated by `prisma migrate dev`) because the local
-- shadow DB is drifted from the migration history. Mirrors what
-- migrate-dev would produce against a clean shadow.

ALTER TABLE "DmIdentity"
  ADD COLUMN IF NOT EXISTS "defaultDmReactions" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

CREATE TABLE IF NOT EXISTS "MessageReaction" (
    "id"        SERIAL          PRIMARY KEY,
    "messageId" TEXT            NOT NULL,
    "userId"    INTEGER         NOT NULL,
    "emoji"     TEXT            NOT NULL,
    "createdAt" TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "MessageReaction_messageId_fkey" FOREIGN KEY ("messageId")
        REFERENCES "Message"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MessageReaction_userId_fkey"    FOREIGN KEY ("userId")
        REFERENCES "DmIdentity"("userId")       ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "MessageReaction_messageId_userId_emoji_key"
    ON "MessageReaction" ("messageId", "userId", "emoji");
CREATE INDEX IF NOT EXISTS "MessageReaction_messageId_idx"
    ON "MessageReaction" ("messageId");
CREATE INDEX IF NOT EXISTS "MessageReaction_userId_idx"
    ON "MessageReaction" ("userId");
