// Read deployed contract addresses out of client/src/abi/addresses.ts so the
// CLI uses the same source of truth as the running app. Avoids the drift
// problem of hand-maintaining a CLI-side shim.
//
// addresses.ts is `export const NAME = '0x...' as const;` lines — trivially
// parseable with a regex. We read it once at module load and freeze.
//
// FRESH-INSTALL FALLBACK
// ----------------------
// On a fresh checkout, addresses.ts doesn't exist yet — it's per-install,
// generated by cli/src/steps/generate.js after the operator picks a client.
// Several CLI steps (validator username lookup, client selection / creation)
// need L1 contract addresses BEFORE generate.js runs. For those callers we
// fall back to reading client/src/abi/deployments.ts — the canonical
// multi-chain manifest, committed and current.
//
// The fallback only resolves L1-side semantic names (CAW_NAMES_*,
// CLIENT_MANAGER_ADDRESS, etc.). Per-client L2 addresses aren't known until
// generate.js writes addresses.ts, but no pre-generate step needs them.

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// addresses.ts lives at repo-root/client/src/abi/addresses.ts; the CLI lives
// at repo-root/cli/src. Resolve once.
const ADDRESSES_TS = path.resolve(__dirname, '../../client/src/abi/addresses.ts')
const DEPLOYMENTS_TS = path.resolve(__dirname, '../../client/src/abi/deployments.ts')

// Optional network hint set by the CLI's networkAndMode step. The fallback
// reader uses this to pick which env block out of deployments.ts to use.
// Defaults to 'testnet' — the same default the rest of the install flow has.
let _network = 'testnet'

export function setNetwork(network) {
  if (network) _network = network
  // Bust the cache so the next load picks up the right env block.
  _cache = null
}

let _cache = null

function load() {
  if (_cache) return _cache
  // Primary source: per-install addresses.ts. Read if it exists.
  if (fs.existsSync(ADDRESSES_TS)) {
    const src = fs.readFileSync(ADDRESSES_TS, 'utf8')
    const re = /export\s+const\s+([A-Z0-9_]+)\s*=\s*["']([^"']+)["']/g
    const out = {}
    let m
    while ((m = re.exec(src)) !== null) {
      out[m[1]] = m[2]
    }
    _cache = Object.freeze(out)
    return _cache
  }
  // Fallback: parse deployments.ts and map L1 contract names to the
  // semantic constants the CLI looks up.
  if (fs.existsSync(DEPLOYMENTS_TS)) {
    _cache = Object.freeze(loadFromDeployments())
    return _cache
  }
  throw new Error(
    `No address source available. Tried ${ADDRESSES_TS} and ${DEPLOYMENTS_TS}.`
  )
}

// Map deployments.ts contract names → the semantic CLI symbols. L1-only;
// anything per-client gets resolved post-generate from the real addresses.ts.
const L1_NAME_MAP = {
  CAW_ADDRESS: 'MintableCaw',
  CAW_NAMES_ADDRESS: 'CawProfile',
  CAW_NAMES_MINTER_ADDRESS: 'CawProfileMinter',
  CAW_NAME_QUOTER_ADDRESS: 'CawProfileQuoter',
  CAW_NAME_MARKETPLACE_ADDRESS: 'CawProfileMarketplace',
  URI_GENERATOR_ADDRESS: 'CawProfileURI',
  CLIENT_MANAGER_ADDRESS: 'CawClientManager',
  CAW_NAMES_L2_MAINNET_ADDRESS: 'CawProfileL2',
  CAW_ACTIONS_MAINNET_ADDRESS: 'CawActions',
}

function loadFromDeployments() {
  const txt = fs.readFileSync(DEPLOYMENTS_TS, 'utf8')
  // Pull the requested env block (testnet / mainnet / dev) out of the
  // exported `deployments` object. Cheap regex parse — same shape that
  // generate.js falls back to when ts-node isn't available.
  const block = parseEnvBlock(txt, _network)
  const l1 = block?.L1 || {}
  const out = {}
  for (const [sym, contractName] of Object.entries(L1_NAME_MAP)) {
    if (l1[contractName]) out[sym] = l1[contractName]
  }
  return out
}

// Find `<env>: { L1: { K: '0x..' }, L2: {...}, … }` inside the deployments
// const literal and return it as a JS object. Only handles L1 (and any
// other top-level chain blocks) at one nesting level — enough for what we
// expose via L1_NAME_MAP.
function parseEnvBlock(txt, env) {
  const envRe = new RegExp(`${env}\\s*:\\s*\\{`, 'g')
  const m = envRe.exec(txt)
  if (!m) return null
  let depth = 1
  let i = m.index + m[0].length
  const start = i
  while (i < txt.length && depth > 0) {
    const c = txt[i]
    if (c === '{') depth++
    else if (c === '}') depth--
    i++
  }
  const body = txt.slice(start, i - 1)
  // Now extract chain blocks: e.g. `L1: { ... }`, `L2: { ... }`.
  const out = {}
  const chainRe = /(\w+)\s*:\s*\{([\s\S]*?)\}/g
  let cm
  while ((cm = chainRe.exec(body)) !== null) {
    const chainName = cm[1]
    const chainBody = cm[2]
    const kv = {}
    const kvRe = /(\w+)\s*:\s*['"]([^'"]+)['"]/g
    let km
    while ((km = kvRe.exec(chainBody)) !== null) {
      kv[km[1]] = km[2]
    }
    out[chainName] = kv
  }
  return out
}

/**
 * Return the address for a given symbol. Reads from per-install addresses.ts
 * when present, falls back to deployments.ts for L1 contracts on a fresh
 * checkout (before generate.js has run).
 *
 * Throws if the symbol can't be resolved from either source — fail-fast
 * beats falling back to a stale shim.
 */
export function addr(name) {
  const all = load()
  const v = all[name]
  if (!v) throw new Error(`Address ${name} not found (looked in addresses.ts and deployments.ts[${_network}].L1)`)
  return v
}

/**
 * Return all addresses as a plain object (useful for debugging).
 */
export function allAddresses() {
  return load()
}
